name: Build

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-docs:
    
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo content
      uses: actions/checkout@v3
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install sphinx furo
    - name: Update Sphinx docs
      run: |
        make html
    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@v4.4
      with:
        branch: gh-pages
        folder: _build
